# File: .github/workflows/deploy-ec2-no-secrets.yml
name: Deploy Portfolio to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@13.126.244.205 << 'EOF'
          cd /home/ubuntu/portfolio
          git reset --hard
          git pull origin main
          docker build -t portfolio:latest .
          docker stop portfolio || true
          docker rm portfolio || true
          docker run -d --name portfolio -p 80:80 portfolio:latest
        EOF
